unique_ids:
  forms:
    Form1: 72MJFEXIN737OQ5IHRZHQPPZJA3SP3DA
  modules: {}
  server_modules: {}
  assets:
    meu_logo_menor_02.png: '168306112604911309558181.413548'
    standard-page.html: MG676C2KUOC72HXTNLCSROZOQG254N6J
    theme.css: LVBQ23DTEIGK2UEPSYLJ43OVNT5S7G32
